---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
    collapse = TRUE,
    comment = "#>",
    dev = 'svglite',
    fig.path = "man/figures/README-",
    fig.showtext = TRUE,
    fig.width = 9,
    fig.height = 6,
    out.width = "100%"
)
```

# Emplot

<!-- badges: start -->
<!-- badges: end -->

A clean theme for `ggplot2` with matching `geom` defaults.

## Installation

Install from [GitHub](https://github.com/) using the [devtools](https://cran.r-project.org/web/packages/devtools) package:

```{r, eval = FALSE}
devtools::install_github("dbarrows/spaceplot")
```

Possible CRAN version in the future.

## Examples

```{r scatter}
library(ggplot2)
library(emplot)

ggplot(mpg, aes(displ, hwy, color = class)) +
    geom_point()
```

```{r histogram}
ggplot(mpg, aes(displ)) +
    geom_histogram(bins = 30)
```

## Options

The grid can be forced on/off with the `grid` option:

```{r grid_off}
ggplot(iris, aes(Sepal.Length, Sepal.Width, color = Species)) +
    geom_point() +
    geom_smooth(method = lm, alpha = 0.25) +
    theme_emplot(grid = FALSE)
```

The font can be changed to a serif with the `serif` option:

```{r serif_on}
ggplot(iris, aes(Petal.Length)) +
    geom_histogram(bins = 30) +
    scale_y_continuous(breaks = seq(5, 25, by = 5)) +
    geom_hline(yintercept = seq(5, 25, by = 5), col = "white", size = 1) +
    theme_emplot(grid = FALSE, serif = TRUE)
```
